"""add user fields

Revision ID: 9962ca20e2fb
Revises: 
Create Date: 2026-06-08 09:56:24.454217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9962ca20e2fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('equipment_photos', sa.Column('url', sa.String(length=1000), nullable=False))
    op.add_column('equipment_photos', sa.Column('filename', sa.String(length=255), nullable=True))
    op.drop_index(op.f('ix_equipment_photos_uploaded_by_id'), table_name='equipment_photos')
    op.drop_column('equipment_photos', 'drive_url')
    op.add_column('equipments', sa.Column('serial_number', sa.String(length=100), nullable=True))
    op.add_column('equipments', sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('equipments', sa.Column('status', sa.Enum('operational', 'maintenance', 'out_of_service', name='equipmentstatus', native_enum=False), nullable=True))
    op.add_column('equipments', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.drop_column('users', 'role')
    op.add_column('work_orders', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.add_column('work_orders', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('work_orders', sa.Column('priority', sa.Enum('low', 'medium', 'high', 'critical', name='wopriority', native_enum=False), nullable=True))
    op.add_column('work_orders', sa.Column('wo_type', sa.Enum('corrective', 'preventive', 'predictive', name='wotype', native_enum=False), nullable=True))
    op.add_column('work_orders', sa.Column('estimated_hours', sa.Float(), nullable=True))
    op.add_column('work_orders', sa.Column('actual_hours', sa.Float(), nullable=True))
    op.add_column('work_orders', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('work_orders', sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('work_orders', 'status',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('open', 'assigned', 'in_progress', 'waiting_parts', 'closed', 'cancelled', name='wostatus', native_enum=False),
               existing_nullable=False)
    op.create_foreign_key(None, 'work_orders', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.alter_column('work_orders', 'status',
               existing_type=sa.Enum('open', 'assigned', 'in_progress', 'waiting_parts', 'closed', 'cancelled', name='wostatus', native_enum=False),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)
    op.drop_column('work_orders', 'closed_at')
    op.drop_column('work_orders', 'due_date')
    op.drop_column('work_orders', 'actual_hours')
    op.drop_column('work_orders', 'estimated_hours')
    op.drop_column('work_orders', 'wo_type')
    op.drop_column('work_orders', 'priority')
    op.drop_column('work_orders', 'title')
    op.drop_column('work_orders', 'created_by_id')
    op.add_column('users', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'position')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'full_name')
    op.drop_column('equipments', 'notes')
    op.drop_column('equipments', 'status')
    op.drop_column('equipments', 'purchase_date')
    op.drop_column('equipments', 'serial_number')
    op.add_column('equipment_photos', sa.Column('drive_url', sa.VARCHAR(length=1000), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_equipment_photos_uploaded_by_id'), 'equipment_photos', ['uploaded_by_id'], unique=False)
    op.drop_column('equipment_photos', 'filename')
    op.drop_column('equipment_photos', 'url')
    op.drop_column('companies', 'created_at')
    # ### end Alembic commands ###
